### PR TITLE
Jupyterlab nvdashboard v0.3.1

### PR DESCRIPTION
**Pull request by owenlamont**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I duplicated this [PR](https://github.com/conda-forge/jupyterlab-nvdashboard-feedstock/pull/5) but updated the bokeh to have a max version of less than 2 and set a minimum run version of jupyterlab to 2 to stop this package installing with jupyterlab 1 which isn't compatible.

Closes https://github.com/conda-forge/jupyterlab-nvdashboard-feedstock/pull/5

### CODE REVIEW

**Review by jacobtomlinson — APPROVED** [review]
This LGTM. @jakirkham can you take a look?

**Comment by owenlamont** [comment]
Thanks for the approval @jacobtomlinson

I was having a couple of second thoughts about this PR which I described on [issue 56](https://github.com/rapidsai/jupyterlab-nvdashboard/issues/56#issuecomment-637586284)

I don't know whether I should make jupyter lab 2 a requirement... I'm not clear on whether the package and the npm versions have to stay in sync or not. The conda-forge recipe as it stands at the moment does requires them to stay in sync which means this recipe no longer works with jupyter lab 1... but if you install the package and labextension seperately it does work in jupyter lab 1 still (it will install the 0.3.1 Python package and version 0.3.0 lab extension if the user is on jupyter lab 1 and that does work - at least at the moment).

**Comment by jacobtomlinson** [comment]
Mt opinion is that moving forwards we should drop JupyterLab 1 support. If folks want to use JupyterLab 1 they can use an older version of the extension.

**Comment by jakirkham** [comment]
If you want to update to 0.3.0 first, that sounds fine to me. Then we can do 0.3.1. Would that work?

**Comment by owenlamont** [comment]
Hi @jakirkham, okay I'll see if I can create a 0.3.0 PR and I'll cap that to jupyter lab 1.

**Comment by owenlamont** [comment]
Hi @jakirkham the 0.3.0 version release [PR](https://github.com/conda-forge/jupyterlab-nvdashboard-feedstock/pull/7) is now up if you'd like to check that. Once you're happy with it I'll merge that first and update this PR.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jacobtomlinson** [comment]
Thanks all for pushing this through.

**Pull request merged**
