### PR TITLE
Updated the bokeh requirements

### PR DESCRIPTION
**Pull request by owenlamont**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Bumping the bokeh requirement to match the rapidsai channel recipe

### CODE REVIEW

**Comment by owenlamont** [comment]
@conda-forge-admin, please rerender

**Comment by owenlamont** [comment]
I tested a local conda build of this recipe and it all appears to be working fine with:

- bokeh 2.1.1 py38h32f6830_0
- jupyterlab 2.2.5 py_0
- jupyterlab-nvdashboard 0.4.0 py_1

**Comment by owenlamont** [comment]
All looks good from my side I think when you have time to check this @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Thanks @owenlamont

**Pull request merged**
